<?xml version="1.0" encoding="UTF-8"?>
<definitions name="BookTrip" targetNamespace="urn://booktrip.ws"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn://booktrip.ws" xmlns:ns="urn://types.fastmoney.imm.dtu.dk" xmlns:ns0="urn://types.travelgood.ws" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="urn://booktrip.ws" xmlns:ns0="urn://types.travelgood.ws" xmlns:ns="urn://types.fastmoney.imm.dtu.dk">
            <xsd:import namespace="urn://types.fastmoney.imm.dtu.dk" schemaLocation="BankService.xsd"/>
            <xsd:import namespace="urn://types.travelgood.ws" schemaLocation="Itinerary.xsd"/>
        </xsd:schema>
    </types>
    <message name="bookItineraryRequest">
        <part name="sessionID" type="xsd:string"/>
        <part name="customerInfo" type="ns:creditCardInfoType"/>
        <part name="inputItineray" type="ns0:Itinerary"/>
    </message>
    <message name="bookItineraryResponse">
        <part name="status" type="xsd:boolean"/>
        <part name="outItinerary" type="ns0:Itinerary"/>
    </message>
    <portType name="BookTripPortType">
        <operation name="bookItinerary">
            <input name="input1" message="tns:bookItineraryRequest"/>
            <output name="output1" message="tns:bookItineraryResponse"/>
        </operation>
    </portType>
    <binding name="BookTripBinding" type="tns:BookTripPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="bookItinerary">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="urn://booktrip.ws"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="urn://booktrip.ws"/>
            </output>
        </operation>
    </binding>
    <service name="BookTripService">
        <port name="BookTripPort" binding="tns:BookTripBinding">
            <soap:address location="http://localhost:9080/BookTripService/BookTripPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="BookTrip">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="BookTripPortTypeRole" portType="tns:BookTripPortType"/>
    </plnk:partnerLinkType>
</definitions>
